services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OyatullohGrafMonteKristo2024!
    ports:
      - "1433:1433"
    networks:
      - sql_network
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    platform: linux/amd64 # ARM64 platformasi

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sinov_app
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=SinovDB;User Id=sa;Password=OyatullohGrafMonteKristo2024!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - sql_network
    volumes:
      - wwwroot_data:/app/wwwroot
    restart: always

networks:
  sql_network:
    driver: bridge

volumes:
  sql_data:
  wwwroot_data:
